<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sphynx\Sphynx.csproj" />
    <ProjectReference Include="lib\dotnet-curses\dotnet-curses\dotnet-curses.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove=".\lib\**\*"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(SolutionName).Test" />
  </ItemGroup>

</Project>
