<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sphynx\Sphynx.csproj" />
    <ProjectReference Include="lib\dotnet-curses\dotnet-curses\dotnet-curses.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove=".\lib\**\*"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(SolutionName).Test" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute"/>
  </ItemGroup>
</Project>

